### ISSUE TITLE
Video record of test with chrome

### ISSUE THREAD

**Issue by generalredneck** [drevops/behat-screenshot#51] opened 2023-05-26 14:19 UTC
I don't know if you have seen this, but I came across this while searching for ways to grab videos of out tests because sometimes it would be helpful to just see things going  through... and we can get some of this with paid services, but want to see if I can do it with chrome and the likes of CircleCI

It looks like it may be possible? and I I'm not sure if this is very simular to what you are doing or not cause I haven't dug through your code, but see https://medium.com/@anchen.li/how-to-do-video-recording-on-headless-chrome-966e10b1221

it's a javascript implementation but maybe we can do something in PHP? It might even be a whole new project... not sure.

**Comment by AlexSkrypnyk** [comment] 2023-10-16 22:58
@generalredneck 
thank you for your suggestion

We are considering adding support for animated Gifs in https://github.com/drevops/behat-screenshot/issues/40 which would provide similar functionality.

I'm closing this as videos would be a duplicate of animated gifs.

**Closed by AlexSkrypnyk** 2023-10-16 22:58 UTC
