### ISSUE TITLE
Install Docker Compose in CircleCI tasks

### ISSUE THREAD

**Issue by xurizaemon** [drevops/behat-screenshot#54] opened 2023-10-15 10:01 UTC
Currently (per #53) I'm seeing some issues with the test configuration of this project.

PRs fail on CircleCI at the step the configuration depends on Docker Compose. The fix for this appears to be the steps in [Installing and using Docker Compose](https://circleci.com/docs/docker-compose/).

**Comment by AlexSkrypnyk** [comment] 2023-10-16 03:26
Closing this as a duplicate of https://github.com/drevops/behat-screenshot/pull/55

**Closed by AlexSkrypnyk** 2023-10-16 03:26 UTC
